sudo: required
services:
    - docker
before_install:
    - docker build -t gusdecool/docker-frontend-test -f Dockerfile.dev .
script:
    - docker run -e CI=true gusdecool/docker-frontend-test npm run test -- --coverage
